version: '2'

services:

  etcd:
    image: quay.io/coreos/etcd:v2.3.7
    hostname: etcd
    ports:
      - "2379:2379"
      - "4001:4001"
    command:
      - -advertise-client-urls=http://0.0.0.0:2379,http://0.0.0.0:4001
      - -listen-client-urls=http://0.0.0.0:2379,http://0.0.0.0:4001

  git2etcd:
    build: .
    image: yapo/git2etcd
    command:
      - /opt/git2etcd/bin/git2etcd
      - -conf_dir=/opt/git2etcd/config
    environment:
      - G2E_REPO_URL=https://github.com/yapo/example_conf.git
      - G2E_ETCD_HOSTS=http://etcd:2379/
    depends_on:
      - etcd
